### ISSUE TITLE
new tag?

### ISSUE THREAD

**Issue by andreineculau** [etrepum/kvc#12]
Thanks for merging the pull requests!

I'm not religious about it, but it would be better to reference a KVC tag, rather than a git hash. Care to consider rolling out one? Thanks

**Comment by etrepum** [comment]
https://github.com/etrepum/kvc/releases/tag/v1.7.0

**Comment by andreineculau** [comment]
Thanks!

On Sat, Mar 12, 2016 at 11:15 PM, Bob Ippolito notifications@github.com
wrote:

> https://github.com/etrepum/kvc/releases/tag/v1.7.0
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/etrepum/kvc/issues/12#issuecomment-195818550.

## 

andreineculau.com http://www.andreineculau.com
